version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
      - ./logs/nginx:/var/log/nginx
    restart: always
    links:
      - wordpress
    networks:
      - wp_network
  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wp_network
    env_file: .env
    restart: always
  wordpress:
    image: wordpress:php7.2-fpm
    ports:
      - '9000:9000'
    container_name: wordpress
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    env_file: .env
    links:
      - mysql
    networks:
      - wp_network
volumes:
  mysql:
networks:
  wp_network: